minimum_pre_commit_version: 1.21.0
repos:
    -   repo: meta
        hooks:
            -   id: check-useless-excludes

    # format Python code with black
    -   repo: https://github.com/psf/black
        rev: 22.1.0
        hooks:
            -   id: black
                language_version: python3

        ## check docstrings
        #- repo: https://github.com/PyCQA/pydocstyle
        #  rev: 5.0.2
        #  hooks:
        #  - id: pydocstyle
        #    args: ["--ignore=D10,D21,D202"]
        #

    # accept proper type annotations only
    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.9.0  # Use the ref you want to point at
        hooks:
            -   id: python-use-type-annotations
            -   id: python-check-blanket-noqa
    # bandit
    -   repo: https://github.com/PyCQA/bandit
        rev: '1.7.2'
        hooks:
            -   id: bandit
                args: [ "-c", ".bandit" ]

    # static type checking with mypy
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.931
        hooks:
            -   id: mypy

    -   repo: https://github.com/pycqa/flake8
        rev: '4.0.1'  # pick a git hash / tag to point to
        hooks:
            -   id: flake8

    # shell scripts
    -   repo: git://github.com/detailyang/pre-commit-shell
        rev: 1.0.5
        hooks:
            -   id: shell-lint
                args: [ --format=json ]

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.31.1
      hooks:
          -     id: markdownlint

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
            -   id: check-added-large-files
            -   id: check-docstring-first
            -   id: debug-statements
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
            -   id: check-ast
            -   id: check-builtin-literals
            -   id: detect-private-key
            -   id: mixed-line-ending
