apiVersion: v2
appVersion: v1.12.5
annotations:
  application.giantswarm.io/team: shield
dependencies:
  - name: kyverno-policies
    version: 3.3.0
description: |
  Kubernetes Pod Security Standards implemented as Kyverno policies
engine: gotpl
home: https://github.com/giantswarm/kyverno-policies
icon: https://s.giantswarm.io/app-icons/kyverno/1/light.svg
keywords:
  - kubernetes
  - policy-agent
  - validating-webhook
  - admission-controller
name: kyverno-policies
restrictions:
  clusterSingleton: true
sources:
  - https://github.com/giantswarm/kyverno-policies
version: 0.21.1
