name: "Test Kyverno Policies with Chainsaw"
on:
  pull_request: {}
  workflow_dispatch: {}
env:
  KIND_VERSION: v0.25.0
  KUBERNETES_VERSION: v1.29.8
  KYVERNO_VERSION: v1.16.0
  HELM_VERSION: 4
jobs:
  test-policies:
    name: "Test Kyverno Policies"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Download kind
        run: |
          curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/bin
      - name: Download kubectl
        run: |
          curl -sLO https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl  && sudo mv kubectl /usr/bin
      - name: Download Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-$HELM_VERSION && chmod +x get_helm.sh && ./get_helm.sh
      - name: Install Make
        run: |
          sudo apt-get update && sudo apt-get install make
      - name: Create kind cluster and install kyverno
        run: |
          make kind-create kind-get-kubeconfig install-kyverno
      - name: Install Kyverno Policies
        run: |
          make install-kyverno-policies